"use client"
import * as React from 'react';
import ResponsiveAppBar from './components/ResponsiveAppBar';

export default function HomeV2() {
  return (
    <main>
      <ResponsiveAppBar />
      <div className="w-full h-full my-10 mx-10">
        <h1 className="font-bold text-xl">Stock App V2</h1>
        <p>Generated by create next app</p>
        <ul>
          <li><a href="/product">Products</a></li>
          <li><a href="/category">Category</a></li>
          <li><a href="/customer">Customer</a></li>
        </ul>
      </div>
    </main>
  );
}